model_name_or_path: /home/zsy/workspace/250606/code/work/260221_gd/data/models/Qwen3-1.7B-HF
stage: "sft"
do_train: true
finetuning_type: "lora"
lora_rank: 8
lora_alpha: 16
lora_dropout: 0.1
lora_target: q_proj,v_proj,k_proj,o_proj
quantization_bit: 4
quantization_method: "bitsandbytes"
dataset: "k12_train_small"
val_size: 0.0
max_samples: 50000
cutoff_len: 512
preprocessing_num_workers: 4
per_device_train_batch_size: 1
gradient_accumulation_steps: 16
num_train_epochs: 2
learning_rate: 0.0003
lr_scheduler_type: "cosine"
warmup_ratio: 0.05
max_grad_norm: 1.0
optim: "adamw_torch"
weight_decay: 0.01
adam_beta1: 0.9
adam_beta2: 0.999
output_dir: /home/zsy/workspace/250606/code/work/260221_gd/finetune/output/qwen3-1.7b-k12-lora
logging_dir: /home/zsy/workspace/250606/code/work/260221_gd/finetune/output/logs
save_strategy: "epoch"
eval_strategy: "no"
logging_steps: 50
save_total_limit: 3
load_best_model_at_end: false
bf16: false
fp16: true
dataloader_num_workers: 0
report_to: "none"
template: "qwen3_nothink"
upcast_layernorm: true
